#CI项目
name: Build ImmortalWrt Firmware

#CI计划
on:
  # 手动执行
  workflow_dispatch:
  # 默认为utc时间，北京时间需要减去8
  # schedule:
  #   - cron: 0 13 1/7 * *

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: ipq60xx-imm
    runs-on: ubuntu-latest
    timeout-minutes: 180

    with:
      #编译平台
      TARGET: ipq60xx-imm
      #源码
      REPO_SOURCE: immortalwrt
      #源码地址
      REPO_URL: https://github.com/VIKINGYFY/immortalwrt.git
      #源码分支
      REPO_BRANCH: main
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/libWrt/wifi.config

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Configure firmware
      run: |
        # 使用基础配置
        cp .config.txt .config
        
        # 设置目标设备
        sed -i 's/CONFIG_TARGET_PROFILE=.*/CONFIG_TARGET_PROFILE="DEVICE_zn_m2"/' .config
        
        # 移除不需要的模块
        sed -i '/CONFIG_PACKAGE_kmod-usb/d' .config
        sed -i '/CONFIG_PACKAGE_kmod-nss/d' .config
        sed -i '/CONFIG_PACKAGE_kmod-qca-nss/d' .config
        sed -i '/CONFIG_PACKAGE_usbutils/d' .config
        
        # 添加OpenClash
        echo "CONFIG_PACKAGE_luci-app-openclash=y" >> .config
        
        # 优化内存占用
        echo "CONFIG_TARGET_OPTIMIZATION=\"-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt\"" >> .config
        echo "CONFIG_TARGET_OPTIONS=\"-fno-caller-saves -fno-plt\"" >> .config
        echo "CONFIG_KERNEL_OPTIMIZATION=\"-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt\"" >> .config
        
        # 仅保留必要功能
        echo "CONFIG_DEFAULT_nss-firmware-ipq60xx=y" >> .config
        echo "CONFIG_DEFAULT_ipq-wifi-zn_m2=y" >> .config
        echo "CONFIG_DEFAULT_kmod-ath11k=y" >> .config
        echo "CONFIG_DEFAULT_kmod-ath11k-ahb=y" >> .config
        
        # 清理配置
        make defconfig

    - name: Build firmware
      run: |
        make -j$(($(nproc) + 1)) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: bin/targets/*/*

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: bin/targets/*/*/*
        body: "ImmortalWrt build for zn_m2 with WiFi and OpenClash"
